In [1]:
from bs4 import BeautifulSoup
from urllib import request
import requests
import pandas as pd
import numpy as np

In [2]:
url = "https://www.boomplay.com/playlists/880218?from=home"
r = requests.get(url)

In [3]:
r.text[0:500]

'\n\n\n\n\n\n\n\n\n\n    \n        \n    \n    \n\n\n\n\n\n\n\n\n\n\n\n<!doctype html>\n<html lang="en">\n<head>\n    <link rel="preconnect" href="https://source.boomplaymusic.com/">\n    <link rel="preconnect" href="https://www.gstatic.com/">\n    <link rel="dns-prefetch" href="https://source.boomplaymusic.com/">\n    <link rel="dns-prefetch" href="https://www.google-analytics.com">\n    <link rel="dns-prefetch" href="https://stats.g.doubleclick.net/">\n    <link rel="dns-prefetch" href="https://www.google.com">\n    <link rel="'

In [4]:
soup = BeautifulSoup(r.text, "html.parser")

In [5]:
# top 100 tracks in africa
songs= soup.find_all("li", attrs= {"class": "clearfix play_one"})
len(songs)

100

In [6]:
# finding the song and artist
song = songs[0]
song1 = song.find_all("a")
song1

[<a class="songName" href="/songs/89708201?from=home">Buga (Lo Lo Lo) ft. Tekno</a>,
 <a class="artistName" href="/artists/1265955?from=home">Kizz Daniel</a>]

In [7]:
# looping through all songs
records = []
for i in songs:
    song_info = i.find_all("a")
    song = song_info[0].text
    artist = song_info[1].text
    print(artist)
    print(song)
    print()
    records.append((song, artist))

Kizz Daniel
Buga (Lo Lo Lo) ft. Tekno

Burna Boy
For My Hand ft. Ed Sheeran

Mavins
Overloading (OVERDOSE) ft. Crayon, Ayra Starr, LADIPOE, Magixx & Boy Spyce

Ruger
Girlfriend

Jay Melody
Nakupenda

Black Sherif
Soja

Fireboy DML
Bandana ft. Asake

Ayra Starr
Rush

Oxlade
KU LO SA - A COLORS SHOW

Rema
Calm Down

Burna Boy
Last Last

Camidoh
Sugarcane Remix

Burna Boy
Common Person

Burna Boy
It's Plenty

Harmonize
Nitaubeba

Magixx
All Over

Zuchu
Fire

Pheelz
Electricity ft. Davido

Pheelz
Finesse ft. Buju

Ruger
WeWe

Lasmid
Friday Night

Barnaba
Hadithi ft. Diamond Platnumz

Black Sherif
Kwaku the Traveller

Lasmid
Atele

Omah Lay
i'm a mess

Marioo
Naogopa ft. Harmonize

Harmonize
Amelowa

Victony
Soweto ft. Tempoe

Ruger
Dior

Asake
Organise

7Teen
Energy

Asake
Terminator

Amerado
Grace ft. Lasmid

Joeboy
Sip (Alcohol)

Fally Ipupa
Bloqué

Barnaba
Marry Me ft. Marioo

Ladé
Adulthood Anthem

Didi B
En Haut ft. Jr La Melo & Tamsir

Phina
Upo Nyonyo

Asake
Joha

Omah Lay
Woman

Patoranking
Kolo Kolo ft. Diamond Platnumz

Gyakie
SOMETHING

D Jay
Balance It

Justin Bieber
Ghost

Ruger
Snapchat

Marioo
Mi Amor ft. Jovial

Asake
Dull

Rayvanny
I Miss You ft. Zuchu

Ruger
Bounce

Rema
Calm Down ft. Selena Gomez

Iyanya
One Side

Marioo
Dear Ex

Lava Lava
Desh Desh

Wendy Shay
Survivor

Burna Boy
Jagele

Chris Brown
Under The Influence

Barnaba
Tamu ft. Nandy

Barnaba
Mzuri ft. Rayvanny

Mabantu
Leo ft. Marioo

Jay Melody
Sugar

Shatta Wale
ON GOD

Yo Maps
Tiliko ft. T-sean

CKay
emiliana

WizKid
Bad To Me

Diamond Platnumz
Mtasubiri (feat. Zuchu)

Dadju
Ambassadeur (Animateur: Brigade)

Fave
Baby Riddim

Platform TZ
Fall ft. Marioo

Fireboy DML
Peru ft. Ed Sheeran

Otile Brown
Jeraha ft. Jovial

Harmonize
Deka ft. Mabantu

Viviane Chidid
Yeuk Yeuk

Asake
Nzaza

FBS
Jo 'Dance ft. Mr Drew

Omah Lay
Understand

Malcolm Nuna
Benzo

VJ
Dans tes bras

ArrDee
Come & Go (Black Sherif Remix)

Kizz Daniel
Lie

Piesie Esther
Wayε Me Yie

Billnass
Bye ft. Nandy

Skiibii
Baddest boy (Remix) ft. Davido

Fireboy DML
All Of Us (Ashawo)

Rayvanny
Te Quiero ft. Marioo

Mayorkun
Certified Loner (No Competition)

Bella Shmurda
Philo ft. Omah Lay

Kizz Daniel
Oshe ft. The Cavemen.

Limo
Tombé pour elle ft. SenSey'

Stonebwoy
GIDIGBA (FIRM & STRONG)

Chile One Mr Zambia
Why Me ft. Chef 187

Asake
Omo Ope ft. Olamide

Kizz Daniel
Pour Me Water

Billnass
Utaonaje ft. Rayvanny

T-Low
Ku Chalo ft. Y Celeb

Crayon
Ijo (Laba Laba)

Asake
Ototo

Asake
Dupe

Didi B
Tala

Anjella
Kioo ft. Harmonize

In [8]:
records[0:3]

[('Buga (Lo Lo Lo) ft. Tekno', 'Kizz Daniel'),
 ('For My Hand ft. Ed Sheeran', 'Burna Boy'),
 ('Overloading (OVERDOSE) ft. Crayon, Ayra Starr, LADIPOE, Magixx & Boy Spyce',
  'Mavins')]

In [9]:
# putting the info in a dataframe
df = pd.DataFrame(records, columns = ["song name", "artist"])
df

                                            song name       artist
0                           Buga (Lo Lo Lo) ft. Tekno  Kizz Daniel
1                          For My Hand ft. Ed Sheeran    Burna Boy
2   Overloading (OVERDOSE) ft. Crayon, Ayra Starr,...       Mavins
3                                          Girlfriend        Ruger
4                                           Nakupenda   Jay Melody
..                                                ...          ...
95                                    Ijo (Laba Laba)       Crayon
96                                              Ototo        Asake
97                                               Dupe        Asake
98                                               Tala       Didi B
99                                 Kioo ft. Harmonize      Anjella

[100 rows x 2 columns]

Top 5 artists with most songs on top 100 in Africa

In [29]:
rank = df.groupby("artist")["song name"].agg(["count"]).sort_values("count", ascending = False)
rank.head(5)

             count
artist
Asake            8
Ruger            5
Burna Boy        5
Kizz Daniel      4
Barnaba          4

Artists whose songs made it to top 100 chart in Africa

In [33]:
t = df.drop_duplicates(subset = "artist", keep = "first")
t[["artist"]]

                 artist
0           Kizz Daniel
1             Burna Boy
2                Mavins
3                 Ruger
4            Jay Melody
..                  ...
89            Stonebwoy
90  Chile One Mr Zambia
94                T-Low
95               Crayon
99              Anjella

[63 rows x 1 columns]

In [34]:
len(t)

63